Repository henriklovhaug/md-tui, pull requests merged in 2024-05, with the labels that each got.

#101 100 images can crash application
  .gitignore
  CHANGELOG.md
  src/main.rs
Labels: bug

#116 107 issue with non alphabetic characters in code block identifier
  CHANGELOG.md
  src/md.pest
Labels: bug

#117 Add Scala syntax highlighting
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/highlight/mod.rs
  src/highlight/scala.rs
Labels: enhancement

#118 104 feature request a binding to open file being viewed with $editor
  CHANGELOG.md
  src/boxes/help_box.rs
  src/event_handler.rs
  src/main.rs
Labels: enhancement

#119 Add more highlighted languages
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/highlight/css.rs
  src/highlight/html.rs
  src/highlight/mod.rs
  src/highlight/php.rs
Labels: enhancement

#123 122 unicode handling issues
  CHANGELOG.md
  src/nodes/textcomponent.rs
Labels: bug

#124 Delay cloning until after viewport check
  CHANGELOG.md
  src/main.rs
  src/pages/markdown_renderer.rs
Labels: performance

#125 120 bug numbered lists are not correctly aligned
  src/main.rs
  src/nodes/textcomponent.rs
  src/search.rs
Labels: bug

#126 50 feature allow key bind config
  CHANGELOG.md
  README.md
  src/boxes/help_box.rs
  src/event_handler.rs
  src/nodes/textcomponent.rs
  src/pages/file_explorer.rs
  src/pages/markdown_renderer.rs
  src/search.rs
  src/util.rs
  src/util/colors.rs
  src/util/keybinds.rs
  src/util/keys.rs
Labels: enhancement

#128 113 small images gets too much room
  CHANGELOG.md
  src/nodes/image.rs
  src/parser.rs
Labels: bug
